services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: multitenant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Joel.-23"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build: .
    command: /app/entrypoint.sh
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  db_data:
